### ISSUE TITLE
رفع نواقصی فایل پروژه

### ISSUE THREAD

**Issue by sepidearaghi** [negareh/diskArak#11]
فولدر پروژه ها ناقص است و بایستی تکمیل گردد

**Comment by shimafaraji** [comment]
:اگر نیاز هست که پروژه ای خارج از موارد موجود در وب سایت قبلی شرکت اضافه شود، موارد زیر به تفکیک هر پروژه ارسال شود:

1. - دسته پروژه
2. - تصاویر
3. - موضوع پروژه
4. - نوع قرارداد
5. - کارفرما
6. - محل اجرا
7. - محل ساخت
8. - محل نصب
9. - درصد انجام کار
10. - سال اجرا
